/*
 * Detail.java
 *
 * Created on Jan 24, 2012, 1:45:27 PM
 */
package view.dialogs;

import javax.swing.table.DefaultTableModel;
import model.beans.SubPiece;
import model.util.PieceUtilities;
import view.notifications.Notifications;

/**
 *
 * @author skuarch
 */
public class Detail extends javax.swing.JDialog {

    private Notifications notifications = null;
    private SubPiece subPiece = null;
    private DefaultTableModel model = null;

    //==========================================================================
    /** Creates new form Detail */
    public Detail(java.awt.Frame parent, boolean modal, SubPiece subPiece) {
        super(parent, modal);
        notifications = new Notifications();
        this.subPiece = subPiece;
        initComponents();
        setLocationRelativeTo(getRootPane());        
        onLoad();
    }

    //==========================================================================
    private void onLoad() {

        if(subPiece == null){
            notifications.error("error subpiece is null", new NullPointerException());
            return;
        }
        
        String[][] subPieceArray = null;

        try {

            setTitle("details " + subPiece.getView());
            String[] columNames = {"Propertie", "Value"};
            subPieceArray = new PieceUtilities().PieceToArray(subPiece);
            jTable1.setModel(new DefaultTableModel(subPieceArray, columNames));

        } catch (Exception e) {
            notifications.error("error creating dialog", e);
        }

    }

    //==========================================================================
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
