/*
 * SaveData.java
 *
 * Created on Oct 12, 2011, 11:03:17 AM
 */
package view.dialogs;

import controllers.ControllerExporter;
import model.beans.SubPiece;
import org.jfree.chart.JFreeChart;
import view.notifications.Notifications;

/**
 *
 * @author skuarch
 */
public class SaveData extends javax.swing.JDialog {

    private Notifications notifications = null;

    //==========================================================================
    /**
     * Creates new form SaveData
     */
    public SaveData(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        notifications = new Notifications();
        initComponents();
        setLocationRelativeTo(getRootPane());
        bar.setIndeterminate(true);
    } // end SaveData

    //=========================================================================
    public void setTextLabelInfo(String text) {
        jLabelInfo.setText(text);
    } // end setTextLabelInfo

    //=========================================================================
    public void removeLoader() {
        jPanel1.remove(jLabelLoader);
    } // end removeLoader

    //=========================================================================
    public void setIndeterminateBar(boolean inditerminate) {
        bar.setIndeterminate(inditerminate);
    } // end setIndeterminateBar

    //==========================================================================
    public void exportTableToExcel(SubPiece subPiece, String path) {

        try {
            EventViewer.getInstance().appendInfoTextConsole("exporting file " + subPiece.getView() + " to " + path);
            new ControllerExporter().exportTableToExcel(subPiece, path);
            setTextLabelInfo("The file has been created");
            setIndeterminateBar(false);
        } catch (Exception e) {
            setVisible(false);
            notifications.error("error creating excel", e);
        }

    } // end exportTableToExcel

    //==========================================================================
    public void exportChartToPDF(JFreeChart chart, SubPiece subPiece, String path) {

        try {
            EventViewer.getInstance().appendInfoTextConsole("exporting file " + subPiece.getView() + " to " + path);
            new ControllerExporter().exportChartToPDF(chart, subPiece, path);
            setTextLabelInfo("The file has been created");
            setIndeterminateBar(false);
        } catch (Exception e) {
            setVisible(false);
            notifications.error("error creating pdf", e);
        }

    } // end createPDF

    //==========================================================================
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLoader = new javax.swing.JLabel();
        jLabelInfo = new javax.swing.JLabel();
        bar = new javax.swing.JProgressBar();
        jButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Save data");

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        jLabelLoader.setText("Saving data");

        jButtonClose.setText("close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLoader, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addComponent(jLabelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addComponent(jButtonClose, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLoader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //==========================================================================
    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCloseActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelLoader;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
